using SmartSentinelEye.EventIngestion.Application.DTOs;

namespace SmartSentinelEye.EventIngestion.Application.Tests.DTOs;

/// <summary>
/// Minimal "the constructor runs and every property is readable"
/// smoke tests for the DTOs. These records are auto-generated by
/// the compiler but coverlet still demands the lines be exercised
/// to count them. Keeps the Application coverage gate honest.
/// </summary>
public class DtoSmokeTests
{
    [Fact]
    public void EventDto_round_trips_every_field()
    {
        Guid id = Guid.CreateVersion7();
        EventDto dto = new(
            id, "munich", "plc", "station-4", "PlcCycleStart",
            DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch.AddSeconds(1), "{}");

        dto.EventIdentifier.ShouldBe(id);
        dto.Fab.ShouldBe("munich");
        dto.Source.ShouldBe("plc");
        dto.Device.ShouldBe("station-4");
        dto.Kind.ShouldBe("PlcCycleStart");
        dto.OccurredAt.ShouldBe(DateTimeOffset.UnixEpoch);
        dto.IngestedAt.ShouldBe(DateTimeOffset.UnixEpoch.AddSeconds(1));
        dto.Payload.ShouldBe("{}");
    }

    [Fact]
    public void EventPageDto_carries_items_and_cursor()
    {
        EventDto[] items =
        [
            new(Guid.CreateVersion7(), "munich", "plc", "s1", "K",
                DateTimeOffset.UnixEpoch, DateTimeOffset.UnixEpoch, "{}"),
        ];
        EventPageDto page = new(items, "next-cursor");

        page.Items.Count.ShouldBe(1);
        page.NextCursor.ShouldBe("next-cursor");
    }

    [Fact]
    public void DeadLetterDto_round_trips_every_field()
    {
        Guid id = Guid.CreateVersion7();
        DeadLetterDto dto = new(
            id, "fab/m/plc/x", "raw", "err", DateTimeOffset.UnixEpoch,
            "munich", "ParseFailure", null, "Held");

        dto.DeadLetterIdentifier.ShouldBe(id);
        dto.Topic.ShouldBe("fab/m/plc/x");
        dto.RawPayload.ShouldBe("raw");
        dto.Error.ShouldBe("err");
        dto.RejectedAt.ShouldBe(DateTimeOffset.UnixEpoch);
        dto.Fab.ShouldBe("munich");
        dto.Reason.ShouldBe("ParseFailure");
        dto.Kind.ShouldBeNull();
        dto.State.ShouldBe("Held");
    }

    /// <summary>T002 (spec 317, #2325) — FR-002/FR-008: a held row's kind is set.</summary>
    [Fact]
    public void DeadLetterDto_carries_a_kind_for_an_unknown_event_type_row()
    {
        DeadLetterDto dto = new(
            Guid.CreateVersion7(), "event/berlin/manual/station-1", "{}", "EVENT_TYPE_HELD: probe",
            DateTimeOffset.UnixEpoch, "berlin", "UnknownEventType", "NobodyDeclaredThis", "Held");

        dto.Kind.ShouldBe("NobodyDeclaredThis");
        dto.Reason.ShouldBe("UnknownEventType");
    }

    [Fact]
    public void WebhookIntegrationDto_round_trips_every_field()
    {
        Guid id = Guid.CreateVersion7();
        WebhookIntegrationDto dto = new(
            id, 7, "qa", "munich", "QaResult", DateTimeOffset.UnixEpoch, RevokedAt: null);

        dto.Identifier.ShouldBe(id);
        dto.Version.ShouldBe(7);
        dto.Name.ShouldBe("qa");
        dto.DefaultKind.ShouldBe("QaResult");
        dto.RegisteredAt.ShouldBe(DateTimeOffset.UnixEpoch);
        dto.RevokedAt.ShouldBeNull();
    }
}
