// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.CameraCatalog.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.CameraCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CameraCatalogDbContext))]
    [Migration("20260903094808_AddIdempotencyKey")]
    partial class AddIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.CameraCatalog.Domain.Camera.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<string>("Fab")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fab");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_normalized")
                        .HasComputedColumnSql("upper(name)", true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("rtsp_url");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Fab", "NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("ux_cameras_fab_name_normalized_active")
                        .HasFilter("status <> 'Decommissioned'");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Fab", "NameNormalized"), "btree");

                    b.ToTable("cameras", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.CameraCatalog.Domain.Camera.Camera", b =>
                {
                    b.OwnsOne("SmartSentinelEye.CameraCatalog.Domain.Camera.Registration", "Registration", b1 =>
                        {
                            b1.Property<Guid>("CameraId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("registered_by");

                            b1.HasKey("CameraId");

                            b1.ToTable("cameras");

                            b1.WithOwner()
                                .HasForeignKey("CameraId");
                        });

                    b.Navigation("Registration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
