// Spec 300 (issue #2349), ADR-0165 §2, T018. The frontend's half of the
// compositor-independent worst-case text legibility rule — the same formula
// as the domain's `TextLegibility` (plan.md §"TextLegibility") and the
// reference generator `text-legibility-vectors.mjs`. `textLegibility.ts` is
// a close transliteration of the generator (ADR-0165 requires independence
// only for the generator itself), pinned below to the generator's committed
// vectors for drift detection between the three — not independent
// derivation, and not a guard against a conceptual error the formula itself
// shares.
//
// `textLegibility.ts` does not exist yet (T018 is RED-first): every import
// below fails to resolve until a later task writes it. That failure IS the
// red state for this file — it is not patched around.
/// <reference types="node" />
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { inkFor, isLegibleTextColor, minimumTextAlpha, parseColor, worstCaseContrasts } from './textLegibility.js';

const here = path.dirname(fileURLToPath(import.meta.url));
// apps/shared/src/ui/composites -> repo root -> tests/OverlayDesigner.Domain.Tests/Overlay/text-legibility-vectors.json
const vectorsPath = path.resolve(
  here,
  '..',
  '..',
  '..',
  '..',
  '..',
  'tests/OverlayDesigner.Domain.Tests/Overlay/text-legibility-vectors.json',
);

interface Vector {
  color: string;
  legible: boolean;
  ink: 'dark' | 'light';
  minimumAlpha: string;
}

function loadVectors(): Vector[] {
  const raw = readFileSync(vectorsPath, 'utf8');
  return JSON.parse(raw) as Vector[];
}

const MINIMUM_CONTRAST = 4.5;

/**
 * An independent, from-scratch re-coding of the same WCAG-derived formula
 * (plan.md §"TextLegibility"), written without reading `textLegibility.ts`'s
 * body, to cross-check the sampled guarantee below. It must NOT be used by
 * the vectors test — that test exercises the function under test directly —
 * only by the sampled-guarantee and monotonicity tests, which exist
 * precisely so two independently-written implementations have to agree.
 */
function independentWorstCaseContrasts(hex: string): { light: number; dark: number } {
  if (!/^#[0-9A-Fa-f]{8}$/.test(hex)) {
    throw new Error(`not an eight-digit colour: ${hex}`);
  }
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const a = parseInt(hex.slice(7, 9), 16) / 255;

  const linearise = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  const relativeLuminance = (cr: number, cg: number, cb: number) =>
    0.2126 * linearise(cr) + 0.7152 * linearise(cg) + 0.0722 * linearise(cb);

  const opaqueLuminance = relativeLuminance(r, g, b);

  const lumEncodedOverWhite = relativeLuminance(a * r + (1 - a), a * g + (1 - a), a * b + (1 - a));
  const lumLinearOverWhite = a * opaqueLuminance + (1 - a);
  const lighter = Math.max(lumEncodedOverWhite, lumLinearOverWhite);

  const lumEncodedOverBlack = relativeLuminance(a * r, a * g, a * b);
  const lumLinearOverBlack = a * opaqueLuminance;
  const darker = Math.min(lumEncodedOverBlack, lumLinearOverBlack);

  const contrastLight = 1.05 / (lighter + 0.05);
  const contrastDark = (darker + 0.05) / 0.05;
  return { light: contrastLight, dark: contrastDark };
}

function toHexByte(value: number): string {
  return value.toString(16).toUpperCase().padStart(2, '0');
}

// 8 RGB-cube corners.
const cubeCorners = ['000000', '0000FF', '00FF00', '00FFFF', 'FF0000', 'FF00FF', 'FFFF00', 'FFFFFF'];

// 6x6x6 = 216 lattice colours over {00,33,66,99,CC,FF} per channel.
const latticeLevels = ['00', '33', '66', '99', 'CC', 'FF'];
const latticeColors: string[] = [];
for (const r of latticeLevels) {
  for (const g of latticeLevels) {
    for (const b of latticeLevels) {
      latticeColors.push(`${r}${g}${b}`);
    }
  }
}

const sampledRgbs = [...cubeCorners, ...latticeColors];

describe('textLegibility (spec 300, FR-015)', () => {
  describe('parseColor', () => {
    it('parses an eight-digit hex colour into 0-1 components', () => {
      expect(parseColor('#D32F2FFF')).toEqual({
        r: 0xd3 / 255,
        g: 0x2f / 255,
        b: 0x2f / 255,
        a: 1,
      });
    });

    it('parses zero alpha and zero RGB', () => {
      expect(parseColor('#00000000')).toEqual({ r: 0, g: 0, b: 0, a: 0 });
    });

    it('parses the default overlay colour', () => {
      expect(parseColor('#FFFFFFD9')).toEqual({
        r: 1,
        g: 1,
        b: 1,
        a: 0xd9 / 255,
      });
    });
  });

  describe('the shared vectors (text-legibility-vectors.json, generated by text-legibility-vectors.mjs)', () => {
    const vectors = loadVectors();

    it('loads at least 150 vectors', () => {
      expect(vectors.length).toBeGreaterThanOrEqual(150);
    });

    it.each(loadVectors().map((vector) => [vector.color, vector] as const))(
      '%s matches legible, ink and minimumAlpha',
      (_color, vector) => {
        expect(isLegibleTextColor(vector.color)).toBe(vector.legible);
        expect(inkFor(vector.color)).toBe(vector.ink);
        expect(minimumTextAlpha(vector.color.slice(1, 7))).toBe(vector.minimumAlpha);
      },
    );
  });

  describe('sampled guarantee: 8 cube corners + 6x6x6 lattice, at minimum alpha and at FF', () => {
    it('reaches at least 4.5 at the computed minimum alpha, independently verified, and the chosen ink is the better one', () => {
      let sampleMinimum = Number.POSITIVE_INFINITY;

      for (const rgb of sampledRgbs) {
        const floorAlpha = minimumTextAlpha(rgb);
        const colorAtFloor = `#${rgb}${floorAlpha}`;

        const independent = independentWorstCaseContrasts(colorAtFloor);
        const chosenInk = inkFor(colorAtFloor);
        const chosenContrast = chosenInk === 'dark' ? independent.dark : independent.light;

        expect(
          chosenContrast,
          `${colorAtFloor}: chosen ink ${chosenInk} only reaches ${chosenContrast.toFixed(4)} independently`,
        ).toBeGreaterThanOrEqual(MINIMUM_CONTRAST);

        sampleMinimum = Math.min(sampleMinimum, chosenContrast);
      }

      expect(sampleMinimum).toBeGreaterThanOrEqual(MINIMUM_CONTRAST);
    });

    it('reaches at least 4.5 at full opacity (FF), independently verified, and the chosen ink is the better one', () => {
      let sampleMinimum = Number.POSITIVE_INFINITY;

      for (const rgb of sampledRgbs) {
        const colorAtFf = `#${rgb}FF`;

        const independent = independentWorstCaseContrasts(colorAtFf);
        const chosenInk = inkFor(colorAtFf);
        const chosenContrast = chosenInk === 'dark' ? independent.dark : independent.light;

        expect(
          chosenContrast,
          `${colorAtFf}: chosen ink ${chosenInk} only reaches ${chosenContrast.toFixed(4)} independently`,
        ).toBeGreaterThanOrEqual(MINIMUM_CONTRAST);

        sampleMinimum = Math.min(sampleMinimum, chosenContrast);
      }

      expect(sampleMinimum).toBeGreaterThanOrEqual(MINIMUM_CONTRAST);
    });

    it("worstCaseContrasts (the function under test) agrees with the test's own independent formula on the sample", () => {
      for (const rgb of sampledRgbs) {
        const floorAlpha = minimumTextAlpha(rgb);
        for (const alphaHex of [floorAlpha, 'FF']) {
          const color = `#${rgb}${alphaHex}`;
          const independent = independentWorstCaseContrasts(color);
          const actual = worstCaseContrasts(color);

          expect(actual.light).toBeCloseTo(independent.light, 6);
          expect(actual.dark).toBeCloseTo(independent.dark, 6);
        }
      }
    });
  });

  describe('monotonicity: legibility never flips true -> false as alpha rises', () => {
    it.each(sampledRgbs)('colour #%s never regresses from legible to illegible as alpha increases', (rgb) => {
      let sawLegible = false;

      for (let alpha = 0; alpha <= 255; alpha += 5) {
        const color = `#${rgb}${toHexByte(alpha)}`;
        const legible = isLegibleTextColor(color);

        if (sawLegible) {
          expect(legible, `#${rgb} at alpha ${toHexByte(alpha)} regressed from legible back to illegible`).toBe(true);
        }

        sawLegible = sawLegible || legible;
      }

      // Alpha 255 (fully opaque) is always exhaustively legible (plan.md
      // §"TextLegibility": "A = 255 is always legible, exhaustive minimum
      // 4.5826").
      expect(isLegibleTextColor(`#${rgb}FF`)).toBe(true);
    });
  });

  describe('minimumTextAlpha', () => {
    it("matches the red vector's floor for white", () => {
      expect(minimumTextAlpha('FFFFFF')).toBe('75');
    });

    it("matches the vector's floor for red (#D32F2F)", () => {
      expect(minimumTextAlpha('D32F2F')).toBe('F9');
    });

    it('is always legible once reached', () => {
      for (const rgb of cubeCorners) {
        const alpha = minimumTextAlpha(rgb);
        expect(isLegibleTextColor(`#${rgb}${alpha}`)).toBe(true);
      }
    });

    it('one step below the computed floor is illegible (the floor is tight, not merely sufficient)', () => {
      for (const rgb of cubeCorners) {
        const alpha = parseInt(minimumTextAlpha(rgb), 16);
        if (alpha === 0) {
          continue;
        }
        const oneBelow = toHexByte(alpha - 1);
        expect(isLegibleTextColor(`#${rgb}${oneBelow}`)).toBe(false);
      }
    });
  });

  describe('isLegibleTextColor boundaries named by the spec', () => {
    it('rejects white one step below its floor (#FFFFFF74)', () => {
      expect(isLegibleTextColor('#FFFFFF74')).toBe(false);
    });

    it('accepts white at its floor (#FFFFFF75)', () => {
      expect(isLegibleTextColor('#FFFFFF75')).toBe(true);
    });

    it('rejects red one step below its floor (#D32F2FF8)', () => {
      expect(isLegibleTextColor('#D32F2FF8')).toBe(false);
    });

    it('accepts red at its floor (#D32F2FF9)', () => {
      expect(isLegibleTextColor('#D32F2FF9')).toBe(true);
    });

    it('rejects red far below its floor (#D32F2F80)', () => {
      expect(isLegibleTextColor('#D32F2F80')).toBe(false);
    });
  });

  describe('inkFor boundaries named by the spec (the opaque threshold pair)', () => {
    it('picks light ink for #757575FF', () => {
      expect(inkFor('#757575FF')).toBe('light');
    });

    it('picks dark ink for #767676FF', () => {
      expect(inkFor('#767676FF')).toBe('dark');
    });
  });
});
