// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.AuditObservability.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.AuditObservability.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditObservabilityDbContext))]
    [Migration("20261006224431_AuditFabAttribution")]
    partial class AuditFabAttribution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.AuditObservability.Domain.AuditEvent.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("Actor")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_identifier");

                    b.Property<string>("ActorUsername")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("actor_username");

                    b.Property<Guid>("EventIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("event_identifier");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_kind");

                    b.Property<string>("Fab")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fab_id");

                    b.Property<string>("FabAttribution")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fab_attribution");

                    b.Property<DateTimeOffset?>("HandlerEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handler_entered_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ResourceIdentifier")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource_identifier");

                    b.Property<string>("ResourceKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("resource_kind");

                    b.Property<short>("SchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset?>("WrittenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("written_at");

                    b.HasKey("Id", "OccurredAt");

                    b.HasIndex("Actor", "OccurredAt")
                        .HasDatabaseName("ix_audit_actor_occurred");

                    b.HasIndex("EventIdentifier", "OccurredAt")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_event_identifier");

                    b.HasIndex("EventKind", "OccurredAt")
                        .HasDatabaseName("ix_audit_kind_occurred");

                    b.HasIndex("Fab", "OccurredAt")
                        .HasDatabaseName("ix_audit_fab_occurred");

                    b.HasIndex("ResourceKind", "ResourceIdentifier", "OccurredAt")
                        .HasDatabaseName("ix_audit_resource_occurred");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.AuditObservability.Domain.AuditEvent.AuditEvent", b =>
                {
                    b.OwnsOne("SmartSentinelEye.AuditObservability.Domain.AuditEvent.StoredPayload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("AuditEventId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("AuditEventOccurredAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("payload");

                            b1.Property<int>("Size")
                                .HasColumnType("integer")
                                .HasColumnName("payload_size_bytes");

                            b1.HasKey("AuditEventId", "AuditEventOccurredAt");

                            b1.ToTable("audit_events");

                            b1.WithOwner()
                                .HasForeignKey("AuditEventId", "AuditEventOccurredAt");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
