// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.OverlayDesigner.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.OverlayDesigner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OverlayDesignerDbContext))]
    [Migration("20261005105722_AddOverlayElementKindAndColour")]
    partial class AddOverlayElementKindAndColour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Overlay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("overlay_id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_overlays_name_active")
                        .HasFilter("archived_at IS NULL");

                    b.ToTable("overlays", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Overlay", b =>
                {
                    b.OwnsOne("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Creation", "Creation", b1 =>
                        {
                            b1.Property<Guid>("OverlayId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.HasKey("OverlayId");

                            b1.ToTable("overlays");

                            b1.WithOwner()
                                .HasForeignKey("OverlayId");
                        });

                    b.OwnsMany("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Revision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("revision_id");

                            b1.Property<DateTimeOffset?>("ArchivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("archived_at");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("revision_number");

                            b1.Property<DateTimeOffset?>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("state");

                            b1.Property<Guid>("overlay_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("overlay_id")
                                .IsUnique()
                                .HasDatabaseName("ux_overlay_revisions_one_published")
                                .HasFilter("state = 'Published'");

                            b1.HasIndex("overlay_id", "Number")
                                .IsUnique()
                                .HasDatabaseName("ux_overlay_revisions_number");

                            b1.ToTable("overlay_revisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("overlay_id");

                            b1.OwnsOne("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Creation", "Creation", b2 =>
                                {
                                    b2.Property<Guid>("RevisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset>("At")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<Guid>("By")
                                        .HasColumnType("uuid")
                                        .HasColumnName("created_by");

                                    b2.HasKey("RevisionId");

                                    b2.ToTable("overlay_revisions");

                                    b2.WithOwner()
                                        .HasForeignKey("RevisionId");
                                });

                            b1.OwnsMany("SmartSentinelEye.OverlayDesigner.Domain.Overlay.OverlayElement", "Elements", b2 =>
                                {
                                    b2.Property<Guid>("revision_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ordinal")
                                        .HasColumnType("integer")
                                        .HasColumnName("ordinal");

                                    b2.Property<string>("Color")
                                        .IsRequired()
                                        .HasMaxLength(9)
                                        .HasColumnType("character varying(9)")
                                        .HasColumnName("color");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("character varying(16)")
                                        .HasColumnName("kind");

                                    b2.HasKey("revision_id", "ordinal");

                                    b2.ToTable("overlay_revision_elements", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("revision_id");

                                    b2.OwnsOne("SmartSentinelEye.OverlayDesigner.Domain.Overlay.NormalizedPosition", "Position", b3 =>
                                        {
                                            b3.Property<Guid>("OverlayElementrevision_id")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("OverlayElementordinal")
                                                .HasColumnType("integer");

                                            b3.Property<decimal>("X")
                                                .HasColumnType("numeric")
                                                .HasColumnName("x");

                                            b3.Property<decimal>("Y")
                                                .HasColumnType("numeric")
                                                .HasColumnName("y");

                                            b3.HasKey("OverlayElementrevision_id", "OverlayElementordinal");

                                            b3.ToTable("overlay_revision_elements");

                                            b3.WithOwner()
                                                .HasForeignKey("OverlayElementrevision_id", "OverlayElementordinal");
                                        });

                                    b2.OwnsOne("SmartSentinelEye.OverlayDesigner.Domain.Overlay.NormalizedSize", "Size", b3 =>
                                        {
                                            b3.Property<Guid>("OverlayElementrevision_id")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("OverlayElementordinal")
                                                .HasColumnType("integer");

                                            b3.Property<decimal>("Height")
                                                .HasColumnType("numeric")
                                                .HasColumnName("height");

                                            b3.Property<decimal>("Width")
                                                .HasColumnType("numeric")
                                                .HasColumnName("width");

                                            b3.HasKey("OverlayElementrevision_id", "OverlayElementordinal");

                                            b3.ToTable("overlay_revision_elements");

                                            b3.WithOwner()
                                                .HasForeignKey("OverlayElementrevision_id", "OverlayElementordinal");
                                        });

                                    b2.OwnsOne("SmartSentinelEye.OverlayDesigner.Domain.Overlay.TextContent", "Text", b3 =>
                                        {
                                            b3.Property<Guid>("OverlayElementrevision_id")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("OverlayElementordinal")
                                                .HasColumnType("integer");

                                            b3.Property<int>("FontSizePx")
                                                .HasColumnType("integer")
                                                .HasColumnName("font_size_px");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasMaxLength(256)
                                                .HasColumnType("character varying(256)")
                                                .HasColumnName("text");

                                            b3.HasKey("OverlayElementrevision_id", "OverlayElementordinal");

                                            b3.ToTable("overlay_revision_elements");

                                            b3.WithOwner()
                                                .HasForeignKey("OverlayElementrevision_id", "OverlayElementordinal");
                                        });

                                    b2.Navigation("Position")
                                        .IsRequired();

                                    b2.Navigation("Size")
                                        .IsRequired();

                                    b2.Navigation("Text");
                                });

                            b1.Navigation("Creation")
                                .IsRequired();

                            b1.Navigation("Elements");
                        });

                    b.Navigation("Creation")
                        .IsRequired();

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
