// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.OverlayDesigner.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.OverlayDesigner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OverlayDesignerDbContext))]
    partial class OverlayDesignerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Overlay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("overlay_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_overlays_name");

                    b.ToTable("overlays", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Overlay", b =>
                {
                    b.OwnsMany("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Revision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("revision_id");

                            b1.Property<DateTimeOffset?>("ArchivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("archived_at");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("revision_number");

                            b1.Property<DateTimeOffset?>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("state");

                            b1.Property<Guid>("overlay_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("overlay_id")
                                .IsUnique()
                                .HasDatabaseName("ux_overlay_revisions_one_published")
                                .HasFilter("state = 'Published'");

                            b1.HasIndex("overlay_id", "Number")
                                .IsUnique()
                                .HasDatabaseName("ux_overlay_revisions_number");

                            b1.ToTable("overlay_revisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("overlay_id");

                            b1.OwnsOne("SmartSentinelEye.OverlayDesigner.Domain.Overlay.Label", "Label", b2 =>
                                {
                                    b2.Property<Guid>("RevisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("FontSizePx")
                                        .HasColumnType("integer")
                                        .HasColumnName("label_font_size_px");

                                    b2.Property<decimal>("NormalizedHeight")
                                        .HasColumnType("numeric")
                                        .HasColumnName("label_height");

                                    b2.Property<decimal>("NormalizedWidth")
                                        .HasColumnType("numeric")
                                        .HasColumnName("label_width");

                                    b2.Property<decimal>("NormalizedX")
                                        .HasColumnType("numeric")
                                        .HasColumnName("label_x");

                                    b2.Property<decimal>("NormalizedY")
                                        .HasColumnType("numeric")
                                        .HasColumnName("label_y");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("label_text");

                                    b2.HasKey("RevisionId");

                                    b2.ToTable("overlay_revisions");

                                    b2.WithOwner()
                                        .HasForeignKey("RevisionId");
                                });

                            b1.Navigation("Label")
                                .IsRequired();
                        });

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
