// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.Identity.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20260903071655_AddIdempotencyKey")]
    partial class AddIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.Identity.Domain.RegisteredClient.RegisteredClient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("registered_client_id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Fab")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fab");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastRotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_rotated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ux_registered_clients_clientid_active")
                        .HasFilter("disabled_at IS NULL");

                    b.HasIndex("Kind", "Fab", "DisabledAt")
                        .HasDatabaseName("ix_registered_clients_kind_fab_disabled");

                    b.ToTable("registered_clients", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.Identity.Domain.RegisteredClient.RegisteredClient", b =>
                {
                    b.OwnsOne("SmartSentinelEye.Identity.Domain.RegisteredClient.Registration", "Registration", b1 =>
                        {
                            b1.Property<Guid>("RegisteredClientId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("registered_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("registered_by");

                            b1.HasKey("RegisteredClientId");

                            b1.ToTable("registered_clients");

                            b1.WithOwner()
                                .HasForeignKey("RegisteredClientId");
                        });

                    b.Navigation("Registration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
