using System.Text.Json;
using System.Text.Json.Serialization;
using SmartSentinelEye.OverlayDesigner.Domain.Overlay;

namespace SmartSentinelEye.OverlayDesigner.Domain.Tests.Overlay;

/// <summary>
/// Spec 300 (#2349), ADR-0165 §2, T006: checks <see cref="TextLegibility"/>
/// against every entry of the shared vectors fixture
/// (<c>text-legibility-vectors.json</c>), generated by the independent
/// reference script <c>text-legibility-vectors.mjs</c> committed beside it.
/// The TypeScript half (<c>textLegibility.test.ts</c>, T018) reads the same
/// file. Only the <c>color</c>/<c>legible</c>/<c>minimumAlpha</c> fields are
/// checked here — <c>ink</c> is a presentation concern the domain does not
/// compute (plan.md §"TextLegibility": "Ink selection stays in the
/// frontend").
/// </summary>
public class TextLegibilityVectorTests
{
    private sealed record Vector(
        [property: JsonPropertyName("color")] string Color,
        [property: JsonPropertyName("legible")] bool Legible,
        [property: JsonPropertyName("ink")] string Ink,
        [property: JsonPropertyName("minimumAlpha")] string MinimumAlpha);

    /// <summary>
    /// Walks up from the test assembly's output directory to the repository
    /// root (marked by the solution file), then down to this fixture's
    /// known path — the same marker-file mechanism
    /// <c>Architecture.Tests.RepositorySource.Root()</c> uses, inlined here
    /// because this test project does not reference that assembly.
    /// </summary>
    private static string FixturePath()
    {
        DirectoryInfo? candidate = new(AppContext.BaseDirectory);
        while (candidate is not null && !File.Exists(Path.Combine(candidate.FullName, "SmartSentinelEye.slnx")))
        {
            candidate = candidate.Parent;
        }

        if (candidate is null)
        {
            throw new InvalidOperationException(
                $"could not locate the repository root above {AppContext.BaseDirectory}");
        }

        return Path.Combine(
            candidate.FullName,
            "tests", "OverlayDesigner.Domain.Tests", "Overlay", "text-legibility-vectors.json");
    }

    private static List<Vector> LoadVectors()
    {
        string json = File.ReadAllText(FixturePath());
        return JsonSerializer.Deserialize<List<Vector>>(json)
            ?? throw new InvalidOperationException("text-legibility-vectors.json deserialised to null.");
    }

    public static IEnumerable<object[]> VectorCases() =>
        LoadVectors().Select(vector => new object[] { vector.Color, vector.Legible, vector.MinimumAlpha });

    [Fact]
    public void The_fixture_is_not_empty()
    {
        LoadVectors().Count.ShouldBeGreaterThan(0);
    }

    [Theory]
    [MemberData(nameof(VectorCases))]
    public void IsLegible_agrees_with_the_independent_reference_generator(
        string color, bool expectedLegible, string expectedMinimumAlphaHex)
    {
        OverlayColor parsed = OverlayColor.From(color);

        TextLegibility.IsLegible(parsed).ShouldBe(expectedLegible, $"colour {color}");
        TextLegibility.MinimumAlpha(parsed).ShouldBe(
            Convert.ToByte(expectedMinimumAlphaHex, 16), $"colour {color}");
    }
}
