// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.LayoutComposition.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.LayoutComposition.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LayoutCompositionDbContext))]
    [Migration("20260527133857_AddLayoutOverlayBinding")]
    partial class AddLayoutOverlayBinding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.LayoutComposition.Domain.Layout.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_layouts_name");

                    b.ToTable("layouts", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.LayoutComposition.Domain.Layout.Layout", b =>
                {
                    b.OwnsMany("SmartSentinelEye.LayoutComposition.Domain.Layout.Revision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("revision_id");

                            b1.Property<DateTimeOffset?>("ArchivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("archived_at");

                            b1.Property<Guid>("Camera")
                                .HasColumnType("uuid")
                                .HasColumnName("camera_id");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("revision_number");

                            b1.Property<Guid?>("Overlay")
                                .HasColumnType("uuid")
                                .HasColumnName("overlay_id");

                            b1.Property<DateTimeOffset?>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("state");

                            b1.Property<Guid>("layout_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("layout_id")
                                .IsUnique()
                                .HasDatabaseName("ux_layout_revisions_one_published")
                                .HasFilter("state = 'Published'");

                            b1.HasIndex("layout_id", "Number")
                                .IsUnique()
                                .HasDatabaseName("ux_layout_revisions_number");

                            b1.ToTable("layout_revisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("layout_id");
                        });

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
