// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.LayoutComposition.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.LayoutComposition.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LayoutCompositionDbContext))]
    [Migration("20260903094827_AddIdempotencyKey")]
    partial class AddIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.LayoutComposition.Domain.Layout.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<string>("Fab")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fab");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Fab")
                        .HasDatabaseName("ix_layouts_fab");

                    b.HasIndex("Fab", "Name")
                        .HasDatabaseName("ix_layouts_fab_name");

                    b.ToTable("layouts", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.LayoutComposition.Domain.Layout.Layout", b =>
                {
                    b.OwnsOne("SmartSentinelEye.LayoutComposition.Domain.Layout.Creation", "Creation", b1 =>
                        {
                            b1.Property<Guid>("LayoutId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.HasKey("LayoutId");

                            b1.ToTable("layouts");

                            b1.WithOwner()
                                .HasForeignKey("LayoutId");
                        });

                    b.OwnsMany("SmartSentinelEye.LayoutComposition.Domain.Layout.Revision", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("revision_id");

                            b1.Property<DateTimeOffset?>("ArchivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("archived_at");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("revision_number");

                            b1.Property<DateTimeOffset?>("PublishedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("published_at");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("state");

                            b1.Property<Guid>("layout_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("layout_id")
                                .IsUnique()
                                .HasDatabaseName("ux_layout_revisions_one_published")
                                .HasFilter("state = 'Published'");

                            b1.HasIndex("layout_id", "Number")
                                .IsUnique()
                                .HasDatabaseName("ux_layout_revisions_number");

                            b1.ToTable("layout_revisions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("layout_id");

                            b1.OwnsOne("SmartSentinelEye.LayoutComposition.Domain.Layout.GridDimensions", "Grid", b2 =>
                                {
                                    b2.Property<Guid>("RevisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Cols")
                                        .HasColumnType("integer")
                                        .HasColumnName("grid_cols");

                                    b2.Property<int>("Rows")
                                        .HasColumnType("integer")
                                        .HasColumnName("grid_rows");

                                    b2.HasKey("RevisionId");

                                    b2.ToTable("layout_revisions");

                                    b2.WithOwner()
                                        .HasForeignKey("RevisionId");
                                });

                            b1.OwnsOne("SmartSentinelEye.LayoutComposition.Domain.Layout.Creation", "Creation", b2 =>
                                {
                                    b2.Property<Guid>("RevisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTimeOffset>("At")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("created_at");

                                    b2.Property<Guid>("By")
                                        .HasColumnType("uuid")
                                        .HasColumnName("created_by");

                                    b2.HasKey("RevisionId");

                                    b2.ToTable("layout_revisions");

                                    b2.WithOwner()
                                        .HasForeignKey("RevisionId");
                                });

                            b1.OwnsMany("SmartSentinelEye.LayoutComposition.Domain.Layout.Tile", "Tiles", b2 =>
                                {
                                    b2.Property<Guid>("revision_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("row")
                                        .HasColumnType("integer")
                                        .HasColumnName("row");

                                    b2.Property<int>("col")
                                        .HasColumnType("integer")
                                        .HasColumnName("col");

                                    b2.Property<Guid>("Camera")
                                        .HasColumnType("uuid")
                                        .HasColumnName("camera_id");

                                    b2.Property<Guid?>("OverlayValue")
                                        .HasColumnType("uuid")
                                        .HasColumnName("overlay_id");

                                    b2.HasKey("revision_id", "row", "col");

                                    b2.HasIndex("OverlayValue")
                                        .HasDatabaseName("ix_layout_revision_tiles_overlay_id");

                                    b2.ToTable("layout_revision_tiles", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("revision_id");
                                });

                            b1.Navigation("Creation")
                                .IsRequired();

                            b1.Navigation("Grid")
                                .IsRequired();

                            b1.Navigation("Tiles");
                        });

                    b.Navigation("Creation")
                        .IsRequired();

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
