// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.StreamDistribution.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.StreamDistribution.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StreamDistributionDbContext))]
    [Migration("20260526155501_InitialStreamDistribution")]
    partial class InitialStreamDistribution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.StreamDistribution.Domain.Stream.Stream", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("stream_id");

                    b.Property<Guid>("Camera")
                        .HasColumnType("uuid")
                        .HasColumnName("camera_id");

                    b.Property<string>("LastError")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("mediamtx_path");

                    b.Property<DateTimeOffset>("ProvisionedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provisioned_at");

                    b.Property<Guid>("ProvisionedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("provisioned_by");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TranscodeMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("transcode_mode");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Camera")
                        .IsUnique()
                        .HasDatabaseName("ux_streams_camera_id");

                    b.HasIndex("Path")
                        .IsUnique()
                        .HasDatabaseName("ux_streams_mediamtx_path");

                    b.ToTable("streams", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
