// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartSentinelEye.Automation.Infrastructure.Persistence;

#nullable disable

namespace SmartSentinelEye.Automation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260903094906_AddIdempotencyKey")]
    partial class AddIdempotencyKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartSentinelEye.Automation.Domain.Rule.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_packed");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Fab")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("fab");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("name");

                    b.Property<string>("Predicate")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("predicate");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TriggerKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trigger_kind");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger_source");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Fab", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_rules_fab_name_active")
                        .HasFilter("state <> 'Archived'");

                    b.HasIndex("Fab", "TriggerSource", "TriggerKind", "State")
                        .HasDatabaseName("ix_rules_fab_trigger_state");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("SmartSentinelEye.Automation.Domain.Rule.Rule", b =>
                {
                    b.OwnsOne("SmartSentinelEye.Automation.Domain.Rule.Creation", "Creation", b1 =>
                        {
                            b1.Property<Guid>("RuleId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("At")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("By")
                                .HasColumnType("uuid")
                                .HasColumnName("created_by");

                            b1.HasKey("RuleId");

                            b1.ToTable("rules");

                            b1.WithOwner()
                                .HasForeignKey("RuleId");
                        });

                    b.Navigation("Creation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
